language: csharp
mono: latest
dotnet: 7.0.100
os:
  - linux
  - osx
sudo: true
dist: xenial
osx_image: xcode13

before_install:
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install dotnet-sdk-3.1 ; fi
 
addons:
  apt:
    sources:
    packages:
script:  
  - echo "----- Restore OPC UA Solution .NET Samples ----------------"
  - dotnet restore "TutorialSamples.sln"
  - dotnet restore "Applications.sln"
  - echo "----- Build OPC UA Solution .NET Applications -------------"
  - dotnet build -c Debug applications/SampleCompany/ReferenceServer/SampleCompany.ReferenceServer.csproj
  - dotnet build -c Release applications/SampleCompany/ReferenceServer/SampleCompany.ReferenceServer.csproj
  - echo "----- Build OPC UA Solution .NET Simulation Sample --------"
  - dotnet build -c Debug examples/Simulation/SampleClient/SampleCompany.SampleClient.csproj
  - dotnet build -c Release examples/Simulation/SampleClient/SampleCompany.SampleClient.csproj
  - dotnet build -c Debug examples/Simulation/SampleServer/SampleCompany.SampleServer.csproj
  - dotnet build -c Release examples/Simulation/SampleServer/SampleCompany.SampleServer.csproj 
  - echo "----- Build OPC UA Solution .NET Tutorials ----------------"
  - dotnet build -c Debug examples/Empty/EmptyServer/EmptyCompany.EmptyServer.csproj
  - dotnet build -c Release examples/Empty/EmptyServer/EmptyCompany.EmptyServer.csproj
  - dotnet build -c Debug examples/Base/SampleServer/SampleCompany.SampleServer.csproj
  - dotnet build -c Release examples/Base/SampleServer/SampleCompany.SampleServer.csproj

  - echo "----- Run OPC UA Solution .NET Simulation Samples ---------"
  - cd examples/Simulation/SampleServer/bin/Debug/net6.0
  - dotnet SampleCompany.SampleServer.dll -t 10 -a
  - cd $TRAVIS_BUILD_DIR
  - ./testclientserversamples.sh

after_script:
  - echo "----- Build done successfully -------------------"

after_failure:
  - echo "----- Build done with error ---------------------"
  - cd $HOME
  - cd .local/share/OPC
  - ls -R
  - cd Logs
  - cd $TRAVIS_BUILD_DIR
