language: csharp
mono: latest
dotnet: 6.0.400
os:
  - linux
  - osx
sudo: true
dist: xenial
osx_image: xcode13

before_install:
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install dotnet-sdk-3.1 ; fi
 
addons:
  apt:
    sources:
    packages:
script:  
  - echo "----- Build OPC UA Solution .NET Applications ---------------"
  - dotnet build applications/SampleCompany/ReferenceServer/SampleCompany.ReferenceServer.csproj -f net6.0 -c Debug 
  - dotnet build applications/SampleCompany/ReferenceServer/SampleCompany.ReferenceServer.csproj -f net6.0 -c Release
  - dotnet build applications/SampleCompany/ReferenceClient/SampleCompany.ReferenceClient.csproj -f net6.0 -c Debug
  - dotnet build applications/SampleCompany/ReferenceClient/SampleCompany.ReferenceClient.csproj -f net6.0 -c Release

  - echo "----- Run OPC UA Solution .NET Reference --------------------"
  - cd applications/SampleCompany/ReferenceServer/bin/Debug/net6.0
  - dotnet SampleCompany.ReferenceServer.dll -t 10 -a
  - cd $TRAVIS_BUILD_DIR
  - ./testclientserversamples.sh

after_script:
  - echo "----- Build done successfully -------------------------------"

after_failure:
  - echo "----- Build done with error ---------------------------------"
  - cd $HOME
  - cd .local/share/OPC
  - ls -R
  - cd Logs
  - cd $TRAVIS_BUILD_DIR
