language: csharp
mono: 6.8.0
dotnet: 3.1.404
os:
  - linux
  - osx
sudo: true
dist: xenial
osx_image: xcode12

before_install:
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install dotnet-sdk-3.1 ; fi
 
addons:
  apt:
    sources:
    packages:
script:  
  - echo "----- Restore OPC UA Solution .NET Samples ------"
  - dotnet restore "NetCoreSamples.sln"
  - echo "----- Build OPC UA Solution .NET Samples --------"
#  - dotnet build -c Debug "examples/Reference/ReferenceServer/Technosoftware.ReferenceServer.csproj"
#  - dotnet build -c Release "examples/Reference/ReferenceServer/Technosoftware.ReferenceServer.csproj"
  - dotnet build -c Debug examples/Workshop/SimpleClient/Technosoftware.SimpleClient.csproj
  - dotnet build -c Release examples/Workshop/SimpleClient/Technosoftware.SimpleClient.csproj
  - dotnet build -c Debug examples/Workshop/ModelDesignClient/Technosoftware.ModelDesignClient.csproj
  - dotnet build -c Release examples/Workshop/ModelDesignClient/Technosoftware.ModelDesignClient.csproj
  - dotnet build -c Debug examples/Workshop/SimpleServer/Technosoftware.SimpleServer.csproj
  - dotnet build -c Release examples/Workshop/SimpleServer/Technosoftware.SimpleServer.csproj 
  - dotnet build -c Debug examples/Workshop/ModelDesignServer/Technosoftware.ModelDesignServer.csproj
  - dotnet build -c Release examples/Workshop/ModelDesignServer/Technosoftware.ModelDesignServer.csproj 

  - echo "----- Run .NET Core samples ---------------------"
  - cd examples/Workshop/ModelDesignServer/bin/Debug/netcoreapp3.1
  - dotnet Technosoftware.ModelDesignServer.dll -t 10 -a
  - cd $TRAVIS_BUILD_DIR
  - cd examples/Workshop/SimpleServer/bin/Debug/netcoreapp3.1
  - dotnet Technosoftware.SimpleServer.dll -t 10 -a
  - cd $TRAVIS_BUILD_DIR
  - ./testclientserversamples.sh

after_script:
  - echo "----- Build done successfully -------------------"

after_failure:
  - echo "----- Build done with error ---------------------"
  - cd $HOME
  - cd .local/share/OPC
  - ls -R
  - cd Logs
  - cd $TRAVIS_BUILD_DIR
