name: 🐞Issue Report (Bug/Change/Enhancement/Question/Help)
description: Create an issue report to help us improve
title: "<title>"
labels: [Needs Investigation]
body:
- type: checkboxes
  attributes:
    label: Type of Issue
    description: Please provide information on the type of issue.
    options:
    - label: Issue
      required: false
    - label: Change
      required: false
    - label: Enhancement
      required: false
    - label: Question
      required: false
    - label: Help wanted
      required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: Please describe the issue you are experience as detailed and consised as possible.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Please provide detailed steps for reproducing the issue.
    placeholder: |
      1. Step 1 '...'
      2. Step 2 '....'
      3. Step 3 '....'
      4. You get it '....'
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: [e.g. Windows 10, Ubuntu, macOS]
        - **Development Environment**: [e.g. Visual Studio 2022 17.2.3]
        - **Runtime**: [e.g. .NET 4.6.2, .NET Core 3.1]
        - **Nuget Version**: [e.g. 2.5.2]        
        - **Component**: [e.g. Technosoftware.UaSolution.UaClient]
        - **Server**: [e.g. \examples\Simulation\SampleServer]
        - **Client**: [e.g. UA Expert]
    value: |
        - OS:
        - Environment:
        - Runtime:
        - Nuget Version:
        - Component:
        - Server:
        - Client: 
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Log files? Code snippets?
      Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
