name: Build .NET 6.0 and .NET 7.0

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build-net6:  
    name: build-net6-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]    
        include:
          - framework: 'net6.0'
            dotnet-version: '6.0.x'
            configuration: 'Release'
            
    env:
      OS: ${{ matrix.os }}
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      CONFIGURATION:  ${{ matrix.configuration }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build
      run: dotnet build  "TutorialSamples.sln" --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }}
     
  build-net7:
    name: build-net7-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]    
        include:
          - framework: 'net7.0'
            dotnet-version: '7.0.x'
            configuration: 'Release'
            
    env:
      OS: ${{ matrix.os }}
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      CONFIGURATION:  ${{ matrix.configuration }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build
      run: dotnet build  "TutorialSamples.sln" --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }}    